name: Har Pito
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Download Ngrok and Scripts
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/Harchanel15/insyaallah-gak-ke-banned-akun-kalian/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Harchanel15/insyaallah-gak-ke-banned-akun-kalian/main/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Harchanel15/insyaallah-gak-ke-banned-akun-kalian/main/loop.bat -OutFile loop.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Harchanel15/insyaallah-gak-ke-banned-akun-kalian/main/start.bat -OutFile push.bat
    - name: Extract Ngrok File
      run: Expand-Archive -Path ngrok.zip -DestinationPath .\ngrok
    - name: Download Google Chrome
      run: Invoke-WebRequest "https://dl.google.com/chrome/install/375.126/chrome_installer.exe" -OutFile chrome_installer.exe
    - name: Install Google Chrome
      run: .\chrome_installer.exe /silent /install
    - name: Connect Ngrok
      run: .\ngrok\ngrok.exe authtoken 2pGqnHynzC7EBJRbpiCL4PzWwT8_6dKMc4WR87UJnqEjLtMkQ
    - name: Configure Windows RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Copy-Item -Path wallpaper.bat -Destination D:\a\wallpaper.bat
    - name: Start Ngrok Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Execute Start Script
      run: cmd /c start.bat
    - name: Execute Loop Script
      run: cmd /c loop.bat
